//
// Created by Hans-Albert Maritz on 23/03/25.
//

#include <stdint.h>
#include "autoconf.h"

#define SERIAL_BRIDGE_CNT CONFIG_ENABLE_SERIAL_BRIDGE_USART0 + CONFIG_ENABLE_SERIAL_BRIDGE_USART1 + CONFIG_ENABLE_SERIAL_BRIDGE_USART2 + CONFIG_ENABLE_SERIAL_BRIDGE_USART3

#define USART0_OFFSET (CONFIG_ENABLE_SERIAL_BRIDGE_USART0 ? 0 : -1)
#define USART1_OFFSET (CONFIG_ENABLE_SERIAL_BRIDGE_USART1 ? (CONFIG_ENABLE_SERIAL_BRIDGE_USART0) : -1)
#define USART2_OFFSET (CONFIG_ENABLE_SERIAL_BRIDGE_USART2 ? (CONFIG_ENABLE_SERIAL_BRIDGE_USART0 + CONFIG_ENABLE_SERIAL_BRIDGE_USART1) : -1)
#define USART3_OFFSET (CONFIG_ENABLE_SERIAL_BRIDGE_USART3 ? (CONFIG_ENABLE_SERIAL_BRIDGE_USART0 + CONFIG_ENABLE_SERIAL_BRIDGE_USART1 + CONFIG_ENABLE_SERIAL_BRIDGE_USART2) : -1)


int8_t serial_bridge_configure(uint8_t usart_number, uint32_t baud, uint8_t enable_u2x);

int8_t serial_bridge_get_buffer_offset_from_usart_number(uint8_t usart_number);
